#!/usr/bin/env python3

import sys
import random

p = float(sys.argv[1]) / 100.0
print(p)

for line in sys.stdin:
	if line[0] in ['@', '%']:
		sys.stdout.write(line)
	elif random.random() <= p:
		sys.stdout.write(line)
