#!/usr/bin/env python3
# Author: Pawel Foremski <pjf@iitis.pl>
# Copyright (C) 2013 IITiS PAN <http://www.iitis.pl/>
# Licensed under GNU GPL v3

import sys
import argparse
import random

def sample(args):
	p = args.percent / 100.0

	for line in sys.stdin:
		if line[0] in ['@', '%']:
			sys.stdout.write(line)
			if args.failed:
				sys.stderr.write(line)
		elif random.random() <= p:
			sys.stdout.write(line)
		elif args.failed:
			sys.stderr.write(line)

if __name__ == "__main__":
	p = argparse.ArgumentParser(description='Sample ARFF lines')
	p.add_argument('percent', type=float, help='line rate (in percents)')
	p.add_argument('-f','--failed', action='store_true', help='write failed lines to stderr')
	args = p.parse_args()

	sample(args)
