#!/usr/bin/env python3
# Author: Pawel Foremski <pjf@iitis.pl>
# Copyright (C) 2013 IITiS PAN <http://www.iitis.pl/>
# Licensed under GNU GPL v3

import sys
import argparse
from ArffReader import *

def readdb(path):
	db = dict()

	f = open(path)
	for line in f:
		line = line.strip()

		if line[0] == "#":
			continue
		else:
			l = line.split()

		db[l[0]] = l[1]

	return db

def rewrite(src, dst, db, column):
	src = ArffReader(src)
	src.printh()

	for d in src:
		val = d[column]
		if val in db:
			d[column] = db[val]
		src.printd(d)

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Rewrite column values in ARFF files')
	parser.add_argument('column', help='column name')
	parser.add_argument('dictionary', help='file with source->destination mappings')
	args = parser.parse_args()

	db = readdb(args.dictionary)
	rewrite(sys.stdin, sys.stdout, db, args.column)
